import * as FileSystem from 'expo-file-system/legacy';
import { SaleInvoiceWithItems } from '../db/queries/sales';
import { PurchaseInvoiceWithItems } from '../db/queries/purchases';
import { toDisplayDate } from '../utils/dateFormat';

export interface ShopProfile {
  id: number;
  name: string;
  address: string;
  phone: string;
  gstin: string;
  currency: string;
  bank_name?: string;
  account_number?: string;
  ifsc?: string;
  upi_id?: string;
  logo_uri?: string;
}

function currencySymbol(currency: string): string {
  const symbols: Record<string, string> = { INR: '₹', USD: '$', EUR: '€', GBP: '£' };
  return symbols[currency] ?? currency;
}

function fmt(amount: number, currency: string): string {
  return `${currencySymbol(currency)}${amount.toFixed(2)}`;
}

async function getBase64Image(uri?: string): Promise<string> {
  if (!uri) return '';
  try {
    const base64 = await FileSystem.readAsStringAsync(uri, { encoding: FileSystem.EncodingType.Base64 });
    return `data:image/jpeg;base64,${base64}`;
  } catch (e) {
    return uri; // Fallback to raw URI if reading fails
  }
}

function getHeader(shop: ShopProfile, logoBase64: string, invoiceNumber: string, date: string, type: 'SALE' | 'PURCHASE', status?: string) {
  const title = type === 'SALE' ? 'ESTIMATE' : 'PURCHASE RECORD';
  const color = type === 'SALE' ? '#1A56DB' : '#0E9F6E';
  return `
  <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:16px;">
    <div style="display:flex;gap:16px;align-items:center;">
      ${logoBase64 ? `<img src="${logoBase64}" style="width:80px;height:80px;object-fit:contain;border-radius:8px;" />` : ''}
      <div>
        <div style="font-size:22px;font-weight:700;color:${color};">${shop.name}</div>
        ${shop.address ? `<div style="margin-top:4px;color:#555;">${shop.address}</div>` : ''}
        ${shop.phone ? `<div style="color:#555;">Ph: ${shop.phone}</div>` : ''}
        ${shop.gstin ? `<div style="color:#555;">GSTIN: ${shop.gstin}</div>` : ''}
      </div>
    </div>
    <div style="text-align:right;">
      <div style="font-size:16px;font-weight:700;color:${color};letter-spacing:1px;">${title}</div>
      <div style="margin-top:4px;color:#555;">Invoice No: <strong>${invoiceNumber}</strong></div>
      <div style="color:#555;">Date: ${toDisplayDate(date)}</div>
      ${status ? `
      <div style="margin-top:4px;display:inline-block;padding:2px 10px;border-radius:12px;font-size:11px;font-weight:600;
        background:${status === 'paid' ? '#d1fae5' : status === 'unpaid' ? '#fee2e2' : '#fef3c7'};
        color:${status === 'paid' ? '#065f46' : status === 'unpaid' ? '#991b1b' : '#92400e'};">
        ${status.toUpperCase()}
      </div>` : ''}
    </div>
  </div>
  <hr style="border:none;border-top:2px solid ${color};margin:16px 0;">`;
}

function getBankDetails(shop: ShopProfile) {
  if (!shop.bank_name && !shop.account_number && !shop.upi_id) return '';
  const upiLink = shop.upi_id ? `upi://pay?pa=${shop.upi_id}&pn=${encodeURIComponent(shop.name)}` : '';
  const qrUrl = upiLink ? `https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=${encodeURIComponent(upiLink)}` : '';

  return `
  <div style="margin-top:24px;padding:16px;border:1px solid #e5e7eb;border-radius:8px;display:flex;justify-content:space-between;align-items:center;background:#f9fafb;">
    <div>
      <div style="font-size:14px;font-weight:700;margin-bottom:8px;color:#374151;">Bank & Payment Details</div>
      ${shop.bank_name ? `<div style="color:#555;margin-bottom:4px;"><strong>Bank:</strong> ${shop.bank_name}</div>` : ''}
      ${shop.account_number ? `<div style="color:#555;margin-bottom:4px;"><strong>Account No:</strong> ${shop.account_number}</div>` : ''}
      ${shop.ifsc ? `<div style="color:#555;margin-bottom:4px;"><strong>IFSC Code:</strong> ${shop.ifsc}</div>` : ''}
      ${shop.upi_id ? `<div style="color:#555;margin-bottom:4px;"><strong>UPI ID:</strong> ${shop.upi_id}</div>` : ''}
    </div>
    ${qrUrl ? `
    <div style="text-align:center;">
      <img src="${qrUrl}" style="width:100px;height:100px;border-radius:4px;" />
      <div style="font-size:10px;color:#6b7280;margin-top:4px;">Scan to Pay</div>
    </div>` : ''}
  </div>`;
}

function getFooter(shop: ShopProfile) {
  return `
  <hr style="border:none;border-top:1px solid #e5e7eb;margin-top:24px;">
  <div style="text-align:center;color:#6b7280;font-size:12px;margin-top:16px;">
    <strong>${shop.name}</strong><br>
    ${shop.address ? `${shop.address} <br>` : ''}
    ${shop.phone ? `Phone: ${shop.phone}` : ''}
  </div>
  <div style="text-align:center;color:#9ca3af;font-size:10px;margin-top:12px;">
    Generated by Bill Kato • ${new Date().toLocaleString()}
  </div>`;
}

export async function buildSaleInvoiceHTML(invoice: SaleInvoiceWithItems, shop: ShopProfile): Promise<string> {
  const sym = currencySymbol(shop.currency);
  const logoBase64 = await getBase64Image(shop.logo_uri);
  
  const itemRows = invoice.items.map((item, i) => `
    <tr style="background:${i % 2 === 0 ? '#ffffff' : '#f9f9f9'}">
      <td style="padding:6px 8px;border:1px solid #e0e0e0;">${i + 1}</td>
      <td style="padding:6px 8px;border:1px solid #e0e0e0;">${item.item_name}</td>
      <td style="padding:6px 8px;border:1px solid #e0e0e0;text-align:center;">${item.quantity}</td>
      <td style="padding:6px 8px;border:1px solid #e0e0e0;text-align:center;">${item.unit}</td>
      <td style="padding:6px 8px;border:1px solid #e0e0e0;text-align:right;">${sym}${item.unit_price.toFixed(2)}</td>
      <td style="padding:6px 8px;border:1px solid #e0e0e0;text-align:center;">${item.discount_pct}%</td>
      <td style="padding:6px 8px;border:1px solid #e0e0e0;text-align:right;font-weight:600;">${sym}${item.line_total.toFixed(2)}</td>
    </tr>
  `).join('');

  const balanceDue = invoice.total - (invoice.amount_paid ?? invoice.total);

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Estimate ${invoice.invoice_number}</title></head>
<body style="font-family:Arial,sans-serif;font-size:13px;padding:32px;color:#1a1a1a;margin:0;">
  ${getHeader(shop, logoBase64, invoice.invoice_number, invoice.invoice_date, 'SALE', invoice.payment_status)}
  <div style="margin-bottom:16px;padding:10px;background:#f0f4ff;border-radius:6px;">
    <strong>Customer:</strong> ${invoice.customer_name || '—'} ${invoice.customer_phone ? `| ${invoice.customer_phone}` : ''}
  </div>
  <table style="width:100%;border-collapse:collapse;margin-bottom:16px;">
    <thead>
      <tr style="background:#1A56DB;color:#fff;">
        <th style="padding:8px;border:1px solid #1A56DB;text-align:left;">#</th>
        <th style="padding:8px;border:1px solid #1A56DB;text-align:left;">Item</th>
        <th style="padding:8px;border:1px solid #1A56DB;text-align:center;">Qty</th>
        <th style="padding:8px;border:1px solid #1A56DB;text-align:center;">Unit</th>
        <th style="padding:8px;border:1px solid #1A56DB;text-align:right;">Rate (${sym})</th>
        <th style="padding:8px;border:1px solid #1A56DB;text-align:center;">Disc%</th>
        <th style="padding:8px;border:1px solid #1A56DB;text-align:right;">Amount (${sym})</th>
      </tr>
    </thead>
    <tbody>${itemRows}</tbody>
  </table>
  <div style="display:flex;justify-content:flex-end;margin-bottom:24px;">
    <div style="width:260px;">
      <div style="display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid #e5e7eb;">
        <span style="color:#555;">Subtotal</span><span>${fmt(invoice.subtotal, shop.currency)}</span>
      </div>
      <div style="display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid #e5e7eb;">
        <span style="color:#555;">Discount</span><span style="color:#e02424;">-${fmt(invoice.discount_amount, shop.currency)}</span>
      </div>
      <div style="display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid #e5e7eb;">
        <span style="color:#555;">Tax</span><span>${fmt(invoice.tax_amount, shop.currency)}</span>
      </div>
      <div style="display:flex;justify-content:space-between;padding:8px 0;margin-top:4px;background:#1A56DB;color:#fff;padding:8px 12px;border-radius:6px;">
        <span style="font-weight:700;font-size:15px;">TOTAL</span>
        <span style="font-weight:700;font-size:15px;">${fmt(invoice.total, shop.currency)}</span>
      </div>
      <div style="display:flex;justify-content:space-between;padding:5px 0;margin-top:4px;border-bottom:1px solid #e5e7eb;">
        <span style="color:#555;">Amount Paid</span><span style="color:#059669;">${fmt(invoice.amount_paid ?? invoice.total, shop.currency)}</span>
      </div>
      <div style="display:flex;justify-content:space-between;padding:5px 0;">
        <span style="color:#555;font-weight:700;">Balance Due</span><span style="font-weight:700;color:${balanceDue > 0 ? '#dc2626' : '#111827'};">${fmt(balanceDue, shop.currency)}</span>
      </div>
    </div>
  </div>
  ${invoice.notes ? `<div style="margin-bottom:16px;padding:10px;background:#f9fafb;border-radius:6px;border-left:3px solid #1A56DB;"><strong>Notes:</strong> ${invoice.notes}</div>` : ''}
  
  ${getBankDetails(shop)}
  ${getFooter(shop)}
</body>
</html>`;
}

export async function buildPurchaseInvoiceHTML(invoice: PurchaseInvoiceWithItems, shop: ShopProfile): Promise<string> {
  const sym = currencySymbol(shop.currency);
  const logoBase64 = await getBase64Image(shop.logo_uri);

  const itemRows = invoice.items.map((item, i) => `
    <tr style="background:${i % 2 === 0 ? '#ffffff' : '#f9f9f9'}">
      <td style="padding:6px 8px;border:1px solid #e0e0e0;">${i + 1}</td>
      <td style="padding:6px 8px;border:1px solid #e0e0e0;">${item.item_name}</td>
      <td style="padding:6px 8px;border:1px solid #e0e0e0;text-align:center;">${item.quantity}</td>
      <td style="padding:6px 8px;border:1px solid #e0e0e0;text-align:center;">${item.unit}</td>
      <td style="padding:6px 8px;border:1px solid #e0e0e0;text-align:right;">${sym}${item.unit_cost.toFixed(2)}</td>
      <td style="padding:6px 8px;border:1px solid #e0e0e0;text-align:right;font-weight:600;">${sym}${item.line_total.toFixed(2)}</td>
    </tr>
  `).join('');

  const balanceDue = invoice.total - (invoice.amount_paid ?? invoice.total);

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Purchase ${invoice.invoice_number}</title></head>
<body style="font-family:Arial,sans-serif;font-size:13px;padding:32px;color:#1a1a1a;margin:0;">
  ${getHeader(shop, logoBase64, invoice.invoice_number, invoice.invoice_date, 'PURCHASE', invoice.payment_status)}
  <div style="margin-bottom:16px;padding:10px;background:#f0fff8;border-radius:6px;">
    <strong>Vendor:</strong> ${invoice.vendor_name || '—'} ${invoice.vendor_phone ? `| ${invoice.vendor_phone}` : ''}
  </div>
  <table style="width:100%;border-collapse:collapse;margin-bottom:16px;">
    <thead>
      <tr style="background:#0E9F6E;color:#fff;">
        <th style="padding:8px;border:1px solid #0E9F6E;text-align:left;">#</th>
        <th style="padding:8px;border:1px solid #0E9F6E;text-align:left;">Item</th>
        <th style="padding:8px;border:1px solid #0E9F6E;text-align:center;">Qty</th>
        <th style="padding:8px;border:1px solid #0E9F6E;text-align:center;">Unit</th>
        <th style="padding:8px;border:1px solid #0E9F6E;text-align:right;">Cost (${sym})</th>
        <th style="padding:8px;border:1px solid #0E9F6E;text-align:right;">Amount (${sym})</th>
      </tr>
    </thead>
    <tbody>${itemRows}</tbody>
  </table>
  <div style="display:flex;justify-content:flex-end;margin-bottom:24px;">
    <div style="width:260px;">
      <div style="display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid #e5e7eb;">
        <span style="color:#555;">Subtotal</span><span>${fmt(invoice.subtotal, shop.currency)}</span>
      </div>
      <div style="display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid #e5e7eb;">
        <span style="color:#555;">Tax</span><span>${fmt(invoice.tax_amount, shop.currency)}</span>
      </div>
      <div style="display:flex;justify-content:space-between;background:#0E9F6E;color:#fff;padding:8px 12px;border-radius:6px;margin-top:4px;">
        <span style="font-weight:700;font-size:15px;">TOTAL</span>
        <span style="font-weight:700;font-size:15px;">${fmt(invoice.total, shop.currency)}</span>
      </div>
      <div style="display:flex;justify-content:space-between;padding:5px 0;margin-top:4px;border-bottom:1px solid #e5e7eb;">
        <span style="color:#555;">Amount Paid</span><span style="color:#059669;">${fmt(invoice.amount_paid ?? invoice.total, shop.currency)}</span>
      </div>
      <div style="display:flex;justify-content:space-between;padding:5px 0;">
        <span style="color:#555;font-weight:700;">Balance Due</span><span style="font-weight:700;color:${balanceDue > 0 ? '#dc2626' : '#111827'};">${fmt(balanceDue, shop.currency)}</span>
      </div>
    </div>
  </div>
  ${invoice.notes ? `<div style="margin-bottom:16px;padding:10px;background:#f9fafb;border-radius:6px;border-left:3px solid #0E9F6E;"><strong>Notes:</strong> ${invoice.notes}</div>` : ''}
  
  ${getFooter(shop)}
</body>
</html>`;
}
